# Create a program that will play the “cows and bulls” game with the user. The game works like this:

# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number(Digits should not be repeated). For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

# Say the number generated by the computer is 1038. An example interaction could look like this:

#   Welcome to the Cows and Bulls Game! 
#   Enter a number: 
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1250
#   1 cow, 1 bull
#   ...
# Until the user guesses the number.



import random

def generate_random():
    digits = random.sample(range(10),4)
    return ''.join(map(str,digits))


match_list = [0 for _ in range(0,4)]


def main():
    print("Welcome to Cows and Bulls Game!")
    secret_number = generate_random()
    print(secret_number)

    bull_count=0
    cow_count=0
    guess_count = 0

    while True:
        guessed_number = input("Enter a 4-digit number: ")
        guess_count+=1

        if len(guessed_number)<4 or not guessed_number.isdigit():
            print("Please Enter a valid 4 digit number: ")
            continue

        if secret_number == guessed_number:
            print("guessed_count ",guess_count)
            print("Bulls=",bull_count," ","Cows=",cow_count)
            break
         
        i=0 
        while(i<len(guessed_number)):
            if(guessed_number[i]==secret_number[i] and not match_list[i]):
                cow_count+=1
                match_list[i]=1
            elif(guessed_number[i]!=secret_number[i] and match_list[i]):
                cow_count-=1
                bull_count+=1
                match_list[i]=0
            i+=1
        print(cow_count," cows",", ",bull_count," bulls")    
 
if __name__ == "__main__":
    main()
         
